services:
  - type: web
    name: ner-logix-platform
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
